/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "HAQQ L2 Documentation",
  "tagline": "HAQQ L2 is a scalable and interoperable Ethereum L2, built on HAQQ Network.",
  "url": "https://l2-docs.haqq.network",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "favicon": "img/favicon.ico",
  "trailingSlash": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "customFields": {
    "project": {
      "name": "HAQQ Network",
      "short_name": "HAQQ",
      "denom": "ETH",
      "ticker": "ETH",
      "binary": "haqqd",
      "testnet_denom": "ETH",
      "testnet_ticker": "ETH",
      "rpc_url": "https://explorer.ethiq.haqq.network/",
      "rpc_url_testnet": "https://explorer.testethiq.haqq.network/",
      "testnet_chain_id": "853211",
      "block_explorer_url": "https://explorer.ethiq.haqq.network/",
      "eth_name": "Ethereum"
    }
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/private/var/www/haqq/l2-docs/sidebars.js",
          "breadcrumbs": true,
          "editUrl": "https://github.com/haqq-network/docs/tree/master/"
        },
        "blog": false,
        "theme": {
          "customCss": "/private/var/www/haqq/l2-docs/src/css/custom.css"
        },
        "sitemap": {
          "lastmod": "datetime",
          "changefreq": "weekly",
          "priority": 0.5
        }
      }
    ]
  ],
  "plugins": [
    [
      "posthog-docusaurus",
      {
        "apiKey": "phc_S8yvZufvPSBgyfXwjP2nIzndGES4HV8i0yOxMecUkLE",
        "appUrl": "https://eu.posthog.com",
        "enableInDevelopment": false
      }
    ],
    null
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "algolia": {
      "appId": "XACAKO6XLW",
      "apiKey": "d30587dac55c28a41cd6aa97878d6e23",
      "indexName": "Haqq Network Documentation",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search",
      "insights": false,
      "askAi": {
        "assistantId": "FL4BAnVxGzJD",
        "indexName": "Haqq Network Documentation",
        "apiKey": "d30587dac55c28a41cd6aa97878d6e23",
        "appId": "XACAKO6XLW"
      }
    },
    "metadata": [
      {
        "name": "keywords",
        "content": "HAQQ, blockchain, ethereum, proof of stake, validator, documentation, islamic blockchain, L2"
      },
      {
        "name": "description",
        "content": "HAQQ L2 is a scalable and interoperable Ethereum L2 blockchain. Explore our comprehensive documentation."
      },
      {
        "property": "og:title",
        "content": "HAQQ L2 Documentation - Ethereum Compatible L2 Platform"
      },
      {
        "property": "og:description",
        "content": "HAQQ L2 is a scalable and interoperable Ethereum L2 blockchain. Explore our comprehensive documentation."
      },
      {
        "name": "sitemap",
        "content": "/sitemap.xml"
      }
    ],
    "navbar": {
      "title": "",
      "logo": {
        "alt": "HAQQ Network",
        "src": "img/haqq-logo.svg",
        "srcDark": "img/haqq-logo-white.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Example Doc"
        },
        {
          "href": "https://github.com/haqq-network/haqq",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "href": "/docs/intro",
              "label": "Introduction"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "HAQQ Network Discord",
              "href": "https://discord.gg/CDtXuQG3Vd"
            },
            {
              "label": "Islamic Coin Discord",
              "href": "https://discord.gg/islamiccoin"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/The_HaqqNetwork"
            },
            {
              "href": "https://github.com/haqq-network/haqq",
              "label": "GitHub"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 HAQQ Network",
      "style": "light"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#9CDCFE",
          "backgroundColor": "#1E1E1E"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "powershell",
        "shell-session",
        "bash",
        "solidity",
        "typescript",
        "toml",
        "yaml",
        "json"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "throw",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
